import { useLanguage } from './i18n/useLanguage'

export const labels = {

  language: 'Language',
  english: 'English',
  hindi: 'Hindi',
  welcome: 'Welcome',
  createAccount: 'Create Account',
  loginSubtitle: 'Login securely with your registered phone number and OTP.',
  signupSubtitle: 'Sign up securely with your phone number and verify OTP.',
  phoneNumber: 'Phone Number',
  fullName: 'Full Name',
  sendOtp: 'Send OTP',
  sendingOtp: 'Sending OTP...',
  verifying: 'Verifying...',
  verifyLogin: 'Verify & Login',
  verifySignup: 'Verify and Sign Up',
  changePhone: 'Change Phone Number',
  noAccount: "Don't have an account?",
  haveAccount: 'Already have an account?',
  signup: 'Sign up',
  login: 'Log in',
  otpSent: 'OTP sent successfully. Use 123456',
  otpSentTo: 'OTP sent to',
  useOtp: 'Use',
  invalidOtp: 'Invalid OTP. Use 123456',
  loginSuccess: 'Login successful',
  signupSuccess: 'Signup successful',
  enterValidPhone: 'Please enter a valid 10 digit phone number',
  enterFullName: 'Please enter your full name',
  buy: 'Buy',
  sell: 'Sell',
  scheme: 'Scheme',
  profile: 'Profile',
  marketplace: 'Marketplace',
  buyHeroTitle: 'Buy smart. Sell fast.',
  buyHeroSubtitle: 'Fresh local deals near you.',
  exploreDeals: 'Explore Deals',
  electronics: 'Electronics',
  electronicsDesc: 'Phones, gadgets, appliances and more',
  vehicles: 'Vehicles',
  vehiclesDesc: 'Cars, bikes and vehicle essentials',
  homeKitchen: 'Home & Kitchen',
  homeKitchenDesc: 'Furniture and everyday home items',
  fashion: 'Fashion',
  fashionDesc: 'Clothing, accessories and style picks',
  searchMarketplace: 'Search Marketplace',
  showingCategory: 'Showing {category} first. Search anything across marketplace.',
  searchInCategory: 'Search in {category}',
  listingsCount: '{count} listings',
  resultsIn: 'Results in {category}',
  bestMatches: 'Best matches in {category}',
  nolistingsFound: 'No listings found',
  tryAnotherSearch: 'Try another search, price, or location.',
  offer: 'Offer',
  verified: 'Verified',
  ratings: 'Ratings',
  view: 'View',
  myListings: 'My Listings',
  listingsSelling: 'listings you are selling',
  add: 'Add',
  all: 'All',
  active: 'Active',
  pending: 'Pending',
  rejected: 'Rejected',
  sold: 'Sold',
  noListingsStatus: 'No {status} listings',
  adminStatusMessage: 'Listings will appear here when admin updates their status.',
  noListingsYet: 'No listings yet',
  addFirstProduct: 'Add your first product with photos, price and seller details.',
  addListing: 'Add Listing',
  sellItem: 'Sell Item',
  addListingDetails: 'Add details to create your listing',
  category: 'Category',
  subcategory: 'Subcategory',
  selectSubcategory: 'Select Subcategory',
  subMobile: 'Mobile',
  subLaptop: 'Laptop',
  subIron: 'Iron',
  subInduction: 'Induction',
  subHeadphones: 'Headphones',
  subSpeaker: 'Speaker',
  subCamera: 'Camera',
  subCar: 'Car',
  subBike: 'Bike',
  subScooter: 'Scooter',
  subCycle: 'Cycle',
  subAutoParts: 'Auto Parts',
  subProperty: 'Property',
  subSofa: 'Sofa',
  subBed: 'Bed',
  subTable: 'Table',
  subChair: 'Chair',
  subMixer: 'Mixer',
  subFridge: 'Fridge',
  subMenWear: 'Men Wear',
  subWomenWear: 'Women Wear',
  subShoes: 'Shoes',
  subBags: 'Bags',
  subWatches: 'Watches',
  subMobiles: 'Mobiles',
  subLaptops: 'Laptops',
  subIrons: 'Irons',
  subInductionCooktops: 'Induction Cooktops',
  subSpeakers: 'Speakers',
  subCameras: 'Cameras',
  subCars: 'Cars',
  subBikes: 'Bikes',
  subScooters: 'Scooters',
  subCycles: 'Cycles',
  subSofas: 'Sofas',
  subBeds: 'Beds',
  subTables: 'Tables',
  subChairs: 'Chairs',
  subMixers: 'Mixers',
  subFridges: 'Fridges',
  listingDetails: 'Listing Details',
  requiredInfo: 'Required info for {item}',
  selectSubcategoryFields: 'Select a subcategory to show product fields',
  ready: 'Ready',
  addCustomField: 'Add custom field',
  addMissingDetail: 'Add any missing detail required for this product.',
  fieldName: 'Field name',
  addProductPhotos: 'Add product photos',
  photoHelp: 'Front, back, bill, scratches or damage',
  sellerName: 'Seller name',
  contactNumber: 'Contact number',
  postListing: 'Post Listing',
  governmentSchemes: 'Government Schemes',
  schemeSubtitle: 'Admin posted schemes for buyers and sellers',
  totalSchemes: 'Total Schemes',
  openNow: 'Open Now',
  benefit: 'Benefit',
  eligibility: 'Eligibility',
  deadline: 'Deadline',
  viewDetails: 'View Details',
  productDetails: 'Product Details',
  buyerViewFor: 'Buyer view for {category}',
  featured: 'Featured',
  overview: 'Overview',
  description: 'Description',
  defaultDescription:
    'This listing is posted by a local seller. Check product condition, warranty, bill availability, accessories, and final price before confirming the deal.',
  askOriginalPhotos: 'Ask for original photos and bill if available.',
  inspectBeforePayment: 'Inspect the product before payment.',
  meetSafeLocation: 'Meet at a safe public location.',
  localSeller: 'Local Seller',
  repliesWithinHour: 'Usually replies within 1 hour',
  safe: 'Safe',
  chat: 'Chat',
  callSeller: 'Call Seller',
  myProfile: 'My Profile',
  manageAccount: 'Manage your account and preferences',
  verifiedUser: 'Verified User',
  myActivity: 'My Activity',
  wishlist: 'Wishlist',
  wishlistDetail: 'Saved listings and favorites',
  myOrders: 'My Orders',
  ordersDetail: 'View your purchase history',
  salesHistory: 'Sales History',
  salesDetail: 'Track sold listings and earnings',
  account: 'Account',
  sellerTools: 'Seller Tools',
  more: 'More',
  back: 'Back',
  likeProduct: 'Like product',
  productBrandModel: 'Product, brand or model',
  searchLocation: 'Search location',
  locationSuggestions: 'Location Suggestions',
  noLocationsFound: 'No locations found',
  suggestions: 'Suggested listings',
  recentSearches: 'Recent Searches',
  clearAll: 'Clear all',
  popularIn: 'Popular in {category}',
  inSeparator: ' in ',
  open: 'Open',
  newScheme: 'New',
  closingSoon: 'Closing Soon',
  expired: 'Expired',
  marketplaceListing: 'Marketplace listing',
  recently: 'Recently',
  today: 'Today',
  yesterday: 'Yesterday',
  daysAgo: '{count} days ago',
  soldYesterday: 'Sold yesterday',
  goodCondition: 'Good Condition',
  likeNew: 'Like New',
  good: 'Good',
  fair: 'Fair',
  needsRepair: 'Needs Repair',
  withWarranty: 'With Warranty',
  noWarranty: 'No Warranty',
  limitedTimeOffer: 'Limited Time Offer',
  popularDeal: 'Popular Deal',
  bestPrice: 'Best Price',
  yes: 'Yes',
  no: 'No',
  selectField: 'Select {field}',
  yourName: 'Your name',
  mobileNumber: 'Mobile number',
  selectedListing: 'Selected listing',
  removeField: 'Remove {field}',
  enterField: 'Enter {field}',
  brand: 'Brand',
  condition: 'Condition',
  warranty: 'Warranty',
  usedFor: 'Used For',
  usage: 'Usage',
  storage: 'Storage',
  ram: 'RAM',
  model: 'Model',
  processor: 'Processor',
  batteryHealth: 'Battery health',
  pickupLocation: 'Pickup location',
  priceNegotiable: 'Price negotiable',
  billAvailable: 'Bill available',
  deliveryOption: 'Delivery option',
  year: 'Year',
  kmDriven: 'KM driven',
  fuelType: 'Fuel type',
  ownership: 'Ownership',
  material: 'Material',
  seatingCapacity: 'Seating capacity',
  dimensions: 'Dimensions',
  capacity: 'Capacity',
  type: 'Type',
  size: 'Size',
  fabric: 'Fabric',
  fit: 'Fit',
  occasion: 'Occasion',
  shop: 'SHOP',
  join: 'JOIN',
}

export const hiLabels = {
  language: 'भाषा',
  english: 'अंग्रेजी',
  hindi: 'हिंदी',
  welcome: 'स्वागत है',
  createAccount: 'खाता बनाएं',
  loginSubtitle: 'अपने रजिस्टर्ड फोन नंबर और OTP से सुरक्षित लॉगिन करें।',
  signupSubtitle: 'अपने फोन नंबर से सुरक्षित साइन अप करें और OTP सत्यापित करें।',
  phoneNumber: 'फोन नंबर',
  fullName: 'पूरा नाम',
  sendOtp: 'OTP भेजें',
  sendingOtp: 'OTP भेजा जा रहा है...',
  verifying: 'सत्यापित हो रहा है...',
  verifyLogin: 'सत्यापित करें और लॉगिन करें',
  verifySignup: 'सत्यापित करें और साइन अप करें',
  changePhone: 'फोन नंबर बदलें',
  noAccount: 'खाता नहीं है?',
  haveAccount: 'पहले से खाता है?',
  signup: 'साइन अप',
  login: 'लॉगिन',
  otpSent: 'OTP सफलतापूर्वक भेजा गया। 123456 उपयोग करें',
  otpSentTo: 'OTP भेजा गया',
  useOtp: 'उपयोग करें',
  invalidOtp: 'गलत OTP। 123456 उपयोग करें',
  loginSuccess: 'लॉगिन सफल',
  signupSuccess: 'साइन अप सफल',
  enterValidPhone: 'कृपया मान्य 10 अंकों का फोन नंबर दर्ज करें',
  enterFullName: 'कृपया अपना पूरा नाम दर्ज करें',
  buy: 'खरीदें',
  sell: 'बेचें',
  scheme: 'योजना',
  profile: 'प्रोफाइल',
  marketplace: 'मार्केटप्लेस',
  buyHeroTitle: 'स्मार्ट खरीदें। जल्दी बेचें।',
  buyHeroSubtitle: 'आपके पास के नए लोकल डील्स।',
  exploreDeals: 'डील्स देखें',
  electronics: 'इलेक्ट्रॉनिक्स',
  electronicsDesc: 'फोन, गैजेट्स, उपकरण और बहुत कुछ',
  vehicles: 'वाहन',
  vehiclesDesc: 'कार, बाइक और वाहन से जुड़ी चीजें',
  homeKitchen: 'घर और किचन',
  homeKitchenDesc: 'फर्नीचर और रोजमर्रा के घरेलू सामान',
  fashion: 'फैशन',
  fashionDesc: 'कपड़े, एक्सेसरीज और स्टाइल आइटम',
  searchMarketplace: 'मार्केटप्लेस खोजें',
  showingCategory: 'पहले {category} दिखाया जा रहा है। मार्केटप्लेस में कुछ भी खोजें।',
  searchInCategory: '{category} में खोजें',
  listingsCount: '{count} प्रोडक्ट',
  resultsIn: '{category} में परिणाम',
  bestMatches: '{category} में सबसे अच्छे मैच',
  nolistingsFound: 'कोई प्रोडक्ट नहीं मिला',
  tryAnotherSearch: 'दूसरी खोज, कीमत या लोकेशन आजमाएं।',
  offer: 'ऑफर',
  verified: 'सत्यापित',
  ratings: 'रेटिंग्स',
  view: 'देखें',
  myListings: 'मेरी लिस्टिंग',
  listingsSelling: 'आपके बेचे जा रहे प्रोडक्ट',
  add: 'जोड़ें',
  all: 'सभी',
  active: 'सक्रिय',
  pending: 'लंबित',
  rejected: 'अस्वीकृत',
  sold: 'बिका हुआ',
  noListingsStatus: '{status} लिस्टिंग नहीं है',
  adminStatusMessage: 'जब एडमिन स्टेटस अपडेट करेगा तो लिस्टिंग यहां दिखेगी।',
  noListingsYet: 'अभी कोई लिस्टिंग नहीं',
  addFirstProduct: 'फोटो, कीमत और विक्रेता जानकारी के साथ अपना पहला प्रोडक्ट जोड़ें।',
  addListing: 'लिस्टिंग जोड़ें',
  sellItem: 'आइटम बेचें',
  addListingDetails: 'अपनी लिस्टिंग बनाने के लिए विवरण जोड़ें',
  category: 'कैटेगरी',
  subcategory: 'सबकैटेगरी',
  selectSubcategory: 'सबकैटेगरी चुनें',
  subMobile: 'मोबाइल',
  subLaptop: 'लैपटॉप',
  subIron: 'आयरन',
  subInduction: 'इंडक्शन',
  subHeadphones: 'हेडफोन',
  subSpeaker: 'स्पीकर',
  subCamera: 'कैमरा',
  subCar: 'कार',
  subBike: 'बाइक',
  subScooter: 'स्कूटर',
  subCycle: 'साइकिल',
  subAutoParts: 'ऑटो पार्ट्स',
  subProperty: 'प्रॉपर्टी',
  subSofa: 'सोफा',
  subBed: 'बेड',
  subTable: 'टेबल',
  subChair: 'चेयर',
  subMixer: 'मिक्सर',
  subFridge: 'फ्रिज',
  subMenWear: 'पुरुष परिधान',
  subWomenWear: 'महिला परिधान',
  subShoes: 'जूते',
  subBags: 'बैग',
  subWatches: 'घड़ियां',
  listingDetails: 'लिस्टिंग विवरण',
  requiredInfo: '{item} के लिए जरूरी जानकारी',
  selectSubcategoryFields: 'प्रोडक्ट फील्ड दिखाने के लिए सबकैटेगरी चुनें',
  ready: 'तैयार',
  addCustomField: 'कस्टम फील्ड जोड़ें',
  addMissingDetail: 'इस प्रोडक्ट के लिए जरूरी कोई अतिरिक्त जानकारी जोड़ें।',
  fieldName: 'फील्ड नाम',
  addProductPhotos: 'प्रोडक्ट फोटो जोड़ें',
  photoHelp: 'आगे, पीछे, बिल, खरोंच या नुकसान',
  sellerName: 'विक्रेता का नाम',
  contactNumber: 'संपर्क नंबर',
  postListing: 'लिस्टिंग पोस्ट करें',
  governmentSchemes: 'सरकारी योजनाएं',
  schemeSubtitle: 'खरीदारों और विक्रेताओं के लिए एडमिन द्वारा पोस्ट की गई योजनाएं',
  totalSchemes: 'कुल योजनाएं',
  openNow: 'अभी खुली',
  benefit: 'लाभ',
  eligibility: 'पात्रता',
  deadline: 'अंतिम तिथि',
  viewDetails: 'विवरण देखें',
  productDetails: 'प्रोडक्ट विवरण',
  buyerViewFor: '{category} के लिए खरीदार व्यू',
  featured: 'फीचर्ड',
  overview: 'ओवरव्यू',
  description: 'विवरण',
  defaultDescription: 'यह लिस्टिंग एक लोकल विक्रेता द्वारा पोस्ट की गई है। डील पक्की करने से पहले प्रोडक्ट की स्थिति, वारंटी, बिल, एक्सेसरीज और अंतिम कीमत जांच लें।',
  askOriginalPhotos: 'यदि उपलब्ध हो तो असली फोटो और बिल मांगें।',
  inspectBeforePayment: 'भुगतान से पहले प्रोडक्ट जांचें।',
  meetSafeLocation: 'सुरक्षित सार्वजनिक स्थान पर मिलें।',
  localSeller: 'लोकल विक्रेता',
  repliesWithinHour: 'आमतौर पर 1 घंटे में जवाब देते हैं',
  safe: 'सुरक्षित',
  chat: 'चैट',
  callSeller: 'विक्रेता को कॉल करें',
  myProfile: 'मेरी प्रोफाइल',
  manageAccount: 'अपना खाता और प्राथमिकताएं प्रबंधित करें',
  verifiedUser: 'सत्यापित यूजर',
  myActivity: 'मेरी गतिविधि',
  wishlist: 'विशलिस्ट',
  wishlistDetail: 'सेव किए गए प्रोडक्ट और पसंदीदा',
  myOrders: 'मेरे ऑर्डर',
  ordersDetail: 'अपनी खरीदारी हिस्ट्री देखें',
  salesHistory: 'सेल्स हिस्ट्री',
  salesDetail: 'बेचे गए प्रोडक्ट और कमाई ट्रैक करें',
  account: 'खाता',
  sellerTools: 'विक्रेता टूल्स',
  more: 'और',
  back: 'वापस',
  likeProduct: 'प्रोडक्ट लाइक करें',
  productBrandModel: 'प्रोडक्ट, ब्रांड या मॉडल',
  searchLocation: 'लोकेशन खोजें',
  locationSuggestions: 'लोकेशन सुझाव',
  noLocationsFound: 'कोई लोकेशन नहीं मिली',
  suggestions: 'सुझाए गए प्रोडक्ट',
  recentSearches: 'हाल की खोजें',
  clearAll: 'सभी हटाएं',
  popularIn: '{category} में लोकप्रिय',
  inSeparator: ' में ',
  open: 'खोलें',
  newScheme: 'नई',
  closingSoon: 'जल्द बंद',
  expired: 'समाप्त',
  marketplaceListing: 'मार्केटप्लेस लिस्टिंग',
  recently: 'हाल ही में',
  today: 'आज',
  yesterday: 'कल',
  daysAgo: '{count} दिन पहले',
  soldYesterday: 'कल बिका',
  goodCondition: 'अच्छी स्थिति',
  likeNew: 'नए जैसा',
  good: 'अच्छा',
  fair: 'ठीक',
  needsRepair: 'मरम्मत चाहिए',
  withWarranty: 'वारंटी के साथ',
  noWarranty: 'बिना वारंटी',
  limitedTimeOffer: 'सीमित समय ऑफर',
  popularDeal: 'लोकप्रिय डील',
  bestPrice: 'सबसे अच्छी कीमत',
  yes: 'हाँ',
  no: 'नहीं',
  selectField: '{field} चुनें',
  yourName: 'आपका नाम',
  mobileNumber: 'मोबाइल नंबर',
  selectedListing: 'चुनी गई लिस्टिंग',
  removeField: '{field} हटाएं',
  enterField: '{field} दर्ज करें',
  brand: 'ब्रांड',
  condition: 'स्थिति',
  warranty: 'वारंटी',
  usedFor: 'कितना इस्तेमाल हुआ',
  usage: 'उपयोग',
  storage: 'स्टोरेज',
  ram: 'RAM',
  model: 'मॉडल',
  processor: 'प्रोसेसर',
  batteryHealth: 'बैटरी हेल्थ',
  pickupLocation: 'पिकअप लोकेशन',
  priceNegotiable: 'कीमत पर बातचीत',
  billAvailable: 'बिल उपलब्ध',
  deliveryOption: 'डिलीवरी विकल्प',
  year: 'वर्ष',
  kmDriven: 'किलोमीटर चला',
  fuelType: 'फ्यूल टाइप',
  ownership: 'मालिकाना',
  material: 'मटेरियल',
  seatingCapacity: 'बैठने की क्षमता',
  dimensions: 'डाइमेंशन',
  capacity: 'क्षमता',
  type: 'प्रकार',
  size: 'साइज',
  fabric: 'कपड़ा',
  fit: 'फिट',
  occasion: 'अवसर',
  shop: 'शॉप',
  join: 'जॉइन',
}

const reverseHindiLabels = Object.entries(labels).reduce((acc, [key, value]) => {
  if (hiLabels[key]) acc[value] = hiLabels[key]
  return acc
}, {})

const formatText = (text, values = {}) =>
  Object.entries(values).reduce(
    (result, [key, value]) => result.replaceAll(`{${key}}`, value),
    text,
  )

export const translateStaticText = (text, language, values = {}) => {
  if (language !== 'hi') return formatText(text, values)

  return formatText(reverseHindiLabels[text] || text, values)
}

export const useAppText = () => {
  const languageContext = useLanguage()

  return {
    language: languageContext.language,
    setLanguage: languageContext.setLanguage,
    translateDynamicText: languageContext.translateDynamicText,
    t: (key, values) => {
      if (languageContext.language === 'hi' && hiLabels[key]) {
        return formatText(hiLabels[key], values)
      }

      return languageContext.translate(formatText(labels[key] || key, values))
    },
  }
}
